from rest_framework import serializers
from django.contrib.auth import get_user_model
from .models import OpenCourtApplication, VideoFeedback, PDFApplication

User = get_user_model()


# =====================================================
# USER SERIALIZER
# =====================================================

class UserSerializer(serializers.ModelSerializer):
    class Meta:
        model = User
        fields = [
            'id', 'username', 'email', 'role', 'phone', 
            'police_station', 'division', 'first_name', 'last_name'
        ]
        read_only_fields = ['id']


# =====================================================
# OPEN COURT APPLICATION SERIALIZER
# =====================================================

class OpenCourtApplicationSerializer(serializers.ModelSerializer):
    # ⭐ CRITICAL FIX: Make sr_no optional (auto-generated by model)
    sr_no = serializers.IntegerField(required=False, allow_null=True)
    
    created_by_name = serializers.CharField(source='created_by.username', read_only=True)
    
    class Meta:
        model = OpenCourtApplication
        fields = [
            'id', 'sr_no', 'dairy_no', 'name', 'contact', 'marked_to', 
            'date', 'marked_by', 'timeline', 'police_station', 'division', 
            'category', 'status', 'days', 'feedback', 'dairy_ps',
            'stipulated_time',
            'remarks', 'video_response', 'supporting_documents',
            'created_at', 'updated_at', 'created_by', 'created_by_name'
        ]
        read_only_fields = ['created_at', 'updated_at', 'created_by']
    
    # ⭐ Override create to handle sr_no properly
    def create(self, validated_data):
        # Remove sr_no from validated_data if it's None or not provided
        # The model's save() method will auto-generate it
        if 'sr_no' in validated_data and validated_data['sr_no'] is None:
            validated_data.pop('sr_no', None)
        
        return super().create(validated_data)


# =====================================================
# STATISTICS SERIALIZERS
# =====================================================

class ApplicationStatsSerializer(serializers.Serializer):
    total_applications = serializers.IntegerField()
    pending = serializers.IntegerField()
    heard = serializers.IntegerField()
    referred = serializers.IntegerField()
    closed = serializers.IntegerField()
    positive_feedback = serializers.IntegerField()
    negative_feedback = serializers.IntegerField()


class CategoryStatsSerializer(serializers.Serializer):
    category = serializers.CharField()
    count = serializers.IntegerField()


class PoliceStationStatsSerializer(serializers.Serializer):
    police_station = serializers.CharField()
    count = serializers.IntegerField()
    pending = serializers.IntegerField()
    heard = serializers.IntegerField()


# =====================================================
# VIDEO FEEDBACK SERIALIZER
# =====================================================

class VideoFeedbackSerializer(serializers.ModelSerializer):
    file_size_mb = serializers.ReadOnlyField()
    reviewed_by_name = serializers.CharField(source='reviewed_by.username', read_only=True)
    
    class Meta:
        model = VideoFeedback
        fields = [
            'id', 'user_name', 'video_file', 'title', 'description',
            'submitted_date', 'admin_feedback', 'admin_remarks',
            'reviewed_by', 'reviewed_by_name', 'reviewed_at',
            'duration', 'file_size', 'file_size_mb', 'thumbnail'
        ]
        read_only_fields = ['submitted_date', 'reviewed_by', 'reviewed_at']


# =====================================================
# PDF APPLICATION SERIALIZER
# =====================================================

class PDFApplicationSerializer(serializers.ModelSerializer):
    file_size_mb = serializers.ReadOnlyField()
    uploaded_by_name = serializers.CharField(source='uploaded_by.username', read_only=True)
    
    # Application details (nested from related OpenCourtApplication)
    dairy_no = serializers.CharField(source='application.dairy_no', read_only=True)
    applicant_name = serializers.CharField(source='application.name', read_only=True)
    police_station = serializers.CharField(source='application.police_station', read_only=True)
    status = serializers.CharField(source='application.status', read_only=True)
    
    # ⭐ FIX: Make these fields NOT required - they'll be auto-populated
    file_name = serializers.CharField(required=False)
    file_size = serializers.IntegerField(required=False)
    
    class Meta:
        model = PDFApplication
        fields = [
            'id', 'application', 'pdf_file', 'file_name', 'file_size', 
            'file_size_mb', 'uploaded_by', 'uploaded_by_name', 'uploaded_at',
            'description', 'dairy_no', 'applicant_name', 'police_station', 'status'
        ]
        read_only_fields = ['uploaded_at', 'uploaded_by']
    
    def create(self, validated_data):
        """Override create to automatically set file metadata"""
        pdf_file = validated_data.get('pdf_file')
        
        # ⭐ FIX: Auto-populate file_name and file_size from uploaded file
        if pdf_file:
            validated_data['file_name'] = pdf_file.name
            validated_data['file_size'] = pdf_file.size
        
        return super().create(validated_data)