import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { 
  FileText, 
  User, 
  Phone, 
  MapPin, 
  Calendar,
  Tag,
  Clock,
  Upload,
  CheckCircle,
  AlertCircle,
  Building,
  FileCheck,
  Save,
  X,
  ArrowLeft,
  Plus,
  Info
} from 'lucide-react';
import { 
  createApplication, 
  getPoliceStations, 
  getCategories,
  getDivisions,
  checkDairyNumber  // ⭐ NEW IMPORT
} from '../services/api';
import { useAuth } from '../context/AuthContext';
import './NewApplication.css';

const NewApplication = () => {
  const navigate = useNavigate();
  const { user } = useAuth();

  // Form state (sr_no removed - auto-generated by backend)
  const [formData, setFormData] = useState({
    dairy_no: '',
    name: '',
    contact: '',
    marked_to: '',
    date: '',
    marked_by: '',
    timeline: '',
    police_station: '',
    division: '',
    category: '',
    status: 'PENDING',
    feedback: 'PENDING',
    stipulated_time: '',
    remarks: '',
  });

  // File states
  const [pdfFile, setPdfFile] = useState(null);
  const [pdfDescription, setPdfDescription] = useState('');

  // Options
  const [policeStations, setPoliceStations] = useState([]);
  const [categories, setCategories] = useState([]);
  const [divisions, setDivisions] = useState([]);

  // Custom category state
  const [showCustomCategory, setShowCustomCategory] = useState(false);
  const [customCategory, setCustomCategory] = useState('');

  // UI states
  const [loading, setLoading] = useState(false);
  const [errors, setErrors] = useState({});
  const [success, setSuccess] = useState('');
  const [error, setError] = useState('');
  
  // ⭐ NEW: Dairy number checking states
  const [checkingDairy, setCheckingDairy] = useState(false);
  const [dairyExists, setDairyExists] = useState(false);
  const [existingAppInfo, setExistingAppInfo] = useState(null);

  // ✅ FIXED: Only 5 status options
  const statusOptions = [
    { value: 'PENDING', label: 'Pending' },
    { value: 'HEARD', label: 'Heard' },
    { value: 'REFERRED', label: 'Referred' },
    { value: 'CLOSED', label: 'Closed' },
    { value: 'BLOCKED', label: 'Blocked' }
  ];

  const feedbackOptions = [
    { value: 'PENDING', label: 'Pending' },
    { value: 'POSITIVE', label: 'Positive' },
    { value: 'NEGATIVE', label: 'Negative' }
  ];

  const stipulatedTimeOptions = [
    '7 days',
    '15 days',
    '20 days',
    '30 days',
    '45 days',
    '60 days',
    '90 days'
  ];

  useEffect(() => {
    fetchDropdownData();
  }, []);

  // ✅ Helper function to remove duplicates (case-insensitive)
  const removeDuplicates = (array) => {
    if (!Array.isArray(array)) return [];
    
    const seen = new Map();
    array.forEach(item => {
      if (item && typeof item === 'string') {
        const normalized = item.trim().toLowerCase();
        if (normalized && !seen.has(normalized)) {
          seen.set(normalized, item.trim());
        }
      }
    });
    
    return Array.from(seen.values()).sort((a, b) => a.localeCompare(b));
  };

  const fetchDropdownData = async () => {
    try {
      const [psData, catData, divData] = await Promise.all([
        getPoliceStations(),
        getCategories(),
        getDivisions()
      ]);
      
      // ✅ Remove duplicates from all dropdowns
      setPoliceStations(removeDuplicates(psData));
      setCategories(removeDuplicates(catData));
      setDivisions(removeDuplicates(divData));
    } catch (error) {
      console.error('Error fetching dropdown data:', error);
    }
  };

  // ⭐ NEW: Check dairy number on blur
  const handleDairyNumberBlur = async () => {
    const dairyNo = formData.dairy_no.trim();
    
    if (!dairyNo) {
      setDairyExists(false);
      setExistingAppInfo(null);
      return;
    }

    setCheckingDairy(true);
    
    try {
      const response = await checkDairyNumber(dairyNo);
      
      if (response.exists) {
        setDairyExists(true);
        setExistingAppInfo(response.application);
        setErrors(prev => ({ 
          ...prev, 
          dairy_no: `This dairy number already exists (SR NO: ${response.application.sr_no})` 
        }));
      } else {
        setDairyExists(false);
        setExistingAppInfo(null);
        setErrors(prev => {
          const newErrors = { ...prev };
          delete newErrors.dairy_no;
          return newErrors;
        });
      }
    } catch (error) {
      console.error('Error checking dairy number:', error);
    } finally {
      setCheckingDairy(false);
    }
  };

  const handleInputChange = (e) => {
    const { name, value } = e.target;
    setFormData(prev => ({
      ...prev,
      [name]: value
    }));
    
    // Clear error for this field
    if (errors[name]) {
      setErrors(prev => ({ ...prev, [name]: '' }));
    }

    // ⭐ Reset dairy check when user changes dairy number
    if (name === 'dairy_no') {
      setDairyExists(false);
      setExistingAppInfo(null);
    }
  };

  const handleCategoryChange = (e) => {
    const value = e.target.value;
    
    if (value === '__ADD_NEW__') {
      setShowCustomCategory(true);
      setFormData(prev => ({ ...prev, category: '' }));
    } else {
      setShowCustomCategory(false);
      setCustomCategory('');
      setFormData(prev => ({ ...prev, category: value }));
    }
  };

  const handleCustomCategoryChange = (e) => {
    const value = e.target.value;
    setCustomCategory(value);
    setFormData(prev => ({ ...prev, category: value }));
    
    if (errors.category) {
      setErrors(prev => ({ ...prev, category: '' }));
    }
  };

  const handlePdfFileChange = (e) => {
    const file = e.target.files[0];
    if (file) {
      if (file.type !== 'application/pdf') {
        setErrors(prev => ({ ...prev, pdfFile: 'Please select a PDF file' }));
        setPdfFile(null);
        return;
      }
      if (file.size > 10 * 1024 * 1024) { // 10MB limit
        setErrors(prev => ({ ...prev, pdfFile: 'PDF file must be less than 10MB' }));
        setPdfFile(null);
        return;
      }
      setPdfFile(file);
      setErrors(prev => ({ ...prev, pdfFile: '' }));
    }
  };

  const validateForm = () => {
    const newErrors = {};

    // Required fields (sr_no removed)
    if (!formData.dairy_no) newErrors.dairy_no = 'Dairy number is required';
    if (!formData.name) newErrors.name = 'Name is required';
    if (!formData.contact) newErrors.contact = 'Contact number is required';
    if (!formData.police_station) newErrors.police_station = 'Police station is required';
    if (!formData.category) newErrors.category = 'Category is required';
    if (!formData.date) newErrors.date = 'Date is required';

    // ⭐ NEW: Check if dairy number exists
    if (dairyExists) {
      newErrors.dairy_no = `Dairy number already exists (SR NO: ${existingAppInfo?.sr_no})`;
    }

    // Contact validation
    if (formData.contact && !/^\d{10,15}$/.test(formData.contact.replace(/[-\s]/g, ''))) {
      newErrors.contact = 'Enter a valid contact number';
    }

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    
    // ⭐ PREVENT SUBMISSION if dairy number exists
    if (dairyExists) {
      setError(`Cannot create application: Dairy number ${formData.dairy_no} already exists!`);
      setTimeout(() => setError(''), 5000);
      return;
    }

    if (!validateForm()) {
      setError('Please fix the errors in the form');
      setTimeout(() => setError(''), 5000);
      return;
    }

    setLoading(true);
    setError('');
    setSuccess('');

    try {
      // Create FormData for file upload
      const submitData = new FormData();
      
      // Append all form fields (sr_no will be auto-generated by backend)
      Object.keys(formData).forEach(key => {
        if (formData[key] !== '') {
          submitData.append(key, formData[key]);
        }
      });

      // Append PDF if present
      if (pdfFile) {
        submitData.append('pdf_application', pdfFile);
        if (pdfDescription) {
          submitData.append('pdf_description', pdfDescription);
        }
      }

      const response = await createApplication(submitData);
      
      setSuccess('Application created successfully!');
      
      // Reset form after 2 seconds and navigate
      setTimeout(() => {
        navigate('/applications');
      }, 2000);

    } catch (error) {
      console.error('Error creating application:', error);
      
      // ⭐ Check for duplicate dairy number error from backend
      if (error.response?.data?.dairy_no) {
        setError(`Dairy number already exists: ${error.response.data.dairy_no}`);
      } else {
        setError(error.response?.data?.error || 'Failed to create application. Please try again.');
      }
    } finally {
      setLoading(false);
    }
  };

  const handleReset = () => {
    setFormData({
      dairy_no: '',
      name: '',
      contact: '',
      marked_to: '',
      date: '',
      marked_by: '',
      timeline: '',
      police_station: '',
      division: '',
      category: '',
      status: 'PENDING',
      feedback: 'PENDING',
      stipulated_time: '',
      remarks: '',
    });
    setPdfFile(null);
    setPdfDescription('');
    setShowCustomCategory(false);
    setCustomCategory('');
    setErrors({});
    setSuccess('');
    setError('');
    setDairyExists(false);
    setExistingAppInfo(null);
  };

  return (
    <div className="new-application-page">
      {/* Header */}
      <div className="page-header-new-app">
        <button className="back-btn" onClick={() => navigate('/applications')}>
          <ArrowLeft size={20} />
          Back to Applications
        </button>
        <div className="header-content">
          <div className="header-icon">
            <FileText size={32} />
          </div>
          <div>
            <h1>New Application Entry</h1>
            <p>Fill out the form below to register a new court application</p>
          </div>
        </div>
      </div>

      {/* Form */}
      <form className="application-form" onSubmit={handleSubmit}>
        
        {/* Section 1: Basic Information */}
        <div className="form-section">
          <div className="section-header">
            <User size={20} />
            <h2>Basic Information</h2>
          </div>
          <div className="form-grid">
            {/* ✅ SR NO REMOVED - Auto-generated by backend */}
            
            <div className="form-group">
              <label className="required">Dairy Number</label>
              <div className="dairy-number-input-wrapper">
                <input
                  type="text"
                  name="dairy_no"
                  value={formData.dairy_no}
                  onChange={handleInputChange}
                  onBlur={handleDairyNumberBlur}
                  placeholder="Enter dairy number"
                  className={errors.dairy_no ? 'error' : dairyExists ? 'error' : ''}
                />
                {checkingDairy && (
                  <span className="checking-indicator">Checking...</span>
                )}
              </div>
              {errors.dairy_no && <span className="error-text">{errors.dairy_no}</span>}
              
              {/* ⭐ Show existing application info */}
              {dairyExists && existingAppInfo && (
                <div className="existing-app-warning">
                  <Info size={16} />
                  <div>
                    <strong>Application already exists:</strong>
                    <div>SR NO: {existingAppInfo.sr_no} | {existingAppInfo.name} | {existingAppInfo.police_station}</div>
                  </div>
                </div>
              )}
            </div>

            <div className="form-group">
              <label className="required">Date</label>
              <div className="input-with-icon">
                <Calendar size={18} />
                <input
                  type="date"
                  name="date"
                  value={formData.date}
                  onChange={handleInputChange}
                  className={errors.date ? 'error' : ''}
                />
              </div>
              {errors.date && <span className="error-text">{errors.date}</span>}
            </div>

            <div className="form-group full-width">
              <label className="required">Applicant Name</label>
              <input
                type="text"
                name="name"
                value={formData.name}
                onChange={handleInputChange}
                placeholder="Enter full name"
                className={errors.name ? 'error' : ''}
              />
              {errors.name && <span className="error-text">{errors.name}</span>}
            </div>

            <div className="form-group">
              <label className="required">Contact Number</label>
              <div className="input-with-icon">
                <Phone size={18} />
                <input
                  type="text"
                  name="contact"
                  value={formData.contact}
                  onChange={handleInputChange}
                  placeholder="03XX-XXXXXXX"
                  className={errors.contact ? 'error' : ''}
                />
              </div>
              {errors.contact && <span className="error-text">{errors.contact}</span>}
            </div>
          </div>
        </div>

        {/* Section 2: Location & Assignment */}
        <div className="form-section">
          <div className="section-header">
            <MapPin size={20} />
            <h2>Location & Assignment Details</h2>
          </div>
          <div className="form-grid">
            <div className="form-group">
              <label className="required">Police Station</label>
              <select
                name="police_station"
                value={formData.police_station}
                onChange={handleInputChange}
                className={errors.police_station ? 'error' : ''}
              >
                <option value="">Select Police Station</option>
                {policeStations.map((ps, idx) => (
                  <option key={idx} value={ps}>{ps}</option>
                ))}
              </select>
              {errors.police_station && <span className="error-text">{errors.police_station}</span>}
            </div>

            <div className="form-group">
              <label>Division</label>
              <select
                name="division"
                value={formData.division}
                onChange={handleInputChange}
              >
                <option value="">Select Division</option>
                {divisions.map((div, idx) => (
                  <option key={idx} value={div}>{div}</option>
                ))}
              </select>
            </div>

            {/* Category with Add New Option */}
            <div className="form-group full-width">
              <label className="required">Category</label>
              {!showCustomCategory ? (
                <div className="category-select-wrapper">
                  <select
                    name="category"
                    value={formData.category}
                    onChange={handleCategoryChange}
                    className={errors.category ? 'error' : ''}
                  >
                    <option value="">Select Category</option>
                    {categories.map((cat, idx) => (
                      <option key={idx} value={cat}>{cat}</option>
                    ))}
                    <option value="__ADD_NEW__">➕ Add New Category</option>
                  </select>
                </div>
              ) : (
                <div className="custom-category-wrapper">
                  <input
                    type="text"
                    value={customCategory}
                    onChange={handleCustomCategoryChange}
                    placeholder="Enter new category name"
                    className={errors.category ? 'error' : ''}
                  />
                  <button
                    type="button"
                    className="cancel-custom-btn"
                    onClick={() => {
                      setShowCustomCategory(false);
                      setCustomCategory('');
                      setFormData(prev => ({ ...prev, category: '' }));
                    }}
                  >
                    <X size={16} />
                    Cancel
                  </button>
                </div>
              )}
              {errors.category && <span className="error-text">{errors.category}</span>}
              {showCustomCategory && (
                <span className="helper-text">
                  <AlertCircle size={14} />
                  Type the new category name and it will be saved with this application
                </span>
              )}
            </div>

            <div className="form-group">
              <label>Marked To</label>
              <input
                type="text"
                name="marked_to"
                value={formData.marked_to}
                onChange={handleInputChange}
                placeholder="Enter marked to"
              />
            </div>

            <div className="form-group">
              <label>Marked By</label>
              <input
                type="text"
                name="marked_by"
                value={formData.marked_by}
                onChange={handleInputChange}
                placeholder="Enter marked by"
              />
            </div>
          </div>
        </div>

        {/* Section 3: Status & Timeline */}
        <div className="form-section">
          <div className="section-header">
            <Clock size={20} />
            <h2>Status & Timeline Management</h2>
          </div>
          <div className="form-grid">
            <div className="form-group">
              <label>Status</label>
              <select
                name="status"
                value={formData.status}
                onChange={handleInputChange}
              >
                {statusOptions.map(opt => (
                  <option key={opt.value} value={opt.value}>{opt.label}</option>
                ))}
              </select>
            </div>

            <div className="form-group">
              <label>Feedback</label>
              <select
                name="feedback"
                value={formData.feedback}
                onChange={handleInputChange}
              >
                {feedbackOptions.map(opt => (
                  <option key={opt.value} value={opt.value}>{opt.label}</option>
                ))}
              </select>
            </div>

            <div className="form-group">
              <label>Stipulated Time</label>
              <select
                name="stipulated_time"
                value={formData.stipulated_time}
                onChange={handleInputChange}
              >
                <option value="">Select Stipulated Time</option>
                {stipulatedTimeOptions.map((time, idx) => (
                  <option key={idx} value={time}>{time}</option>
                ))}
              </select>
            </div>

            <div className="form-group">
              <label>Timeline</label>
              <input
                type="text"
                name="timeline"
                value={formData.timeline}
                onChange={handleInputChange}
                placeholder="Enter timeline details"
              />
            </div>

            <div className="form-group full-width">
              <label>Remarks</label>
              <textarea
                name="remarks"
                value={formData.remarks}
                onChange={handleInputChange}
                placeholder="Enter any additional remarks or notes..."
                rows="4"
              />
            </div>
          </div>
        </div>

        {/* Section 4: PDF Document Upload */}
        <div className="form-section">
          <div className="section-header">
            <Upload size={20} />
            <h2>PDF Application Upload (Optional)</h2>
          </div>
          
          <div className="form-grid">
            {/* PDF Application Upload */}
            <div className="form-group full-width">
              <label>PDF Application Document</label>
              <div className="file-upload-area">
                <input
                  type="file"
                  id="pdf-file"
                  accept="application/pdf"
                  onChange={handlePdfFileChange}
                  style={{ display: 'none' }}
                />
                <label htmlFor="pdf-file" className="file-upload-label">
                  <FileCheck size={24} />
                  <span>{pdfFile ? pdfFile.name : 'Choose PDF File'}</span>
                  <small>PDF only, max 10MB</small>
                </label>
                {pdfFile && (
                  <button
                    type="button"
                    className="remove-file-btn"
                    onClick={() => setPdfFile(null)}
                  >
                    <X size={16} /> Remove
                  </button>
                )}
              </div>
              {errors.pdfFile && <span className="error-text">{errors.pdfFile}</span>}
            </div>

            {pdfFile && (
              <div className="form-group full-width">
                <label>PDF Description</label>
                <input
                  type="text"
                  value={pdfDescription}
                  onChange={(e) => setPdfDescription(e.target.value)}
                  placeholder="Brief description of the PDF document"
                />
              </div>
            )}
          </div>
        </div>

        {/* Form Actions */}
        <div className="form-actions">
          {/* ⭐ Messages shown above buttons */}
          {(success || error) && (
            <div className="form-message-container">
              {success && (
                <div className="form-message success">
                  <CheckCircle size={20} />
                  <span>{success}</span>
                </div>
              )}
              {error && (
                <div className="form-message error">
                  <AlertCircle size={20} />
                  <span>{error}</span>
                </div>
              )}
            </div>
          )}
          
          <button
            type="button"
            className="btn btn-secondary"
            onClick={handleReset}
            disabled={loading}
          >
            <X size={20} />
            Reset Form
          </button>
          <button
            type="submit"
            className="btn btn-primary"
            disabled={loading || dairyExists}
          >
            {loading ? (
              <>
                <div className="spinner-small"></div>
                Creating...
              </>
            ) : (
              <>
                <Save size={20} />
                Create Application
              </>
            )}
          </button>
        </div>
      </form>
    </div>
  );
};

export default NewApplication;