# Generated by Django 6.0.1 on 2026-02-14 03:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_opencourtapplication_idx_police_station_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PDFApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pdf_file", models.FileField(upload_to="pdf_applications/")),
                ("file_name", models.CharField(max_length=300)),
                ("file_size", models.BigIntegerField(help_text="File size in bytes")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("description", models.TextField(blank=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pdf_documents",
                        to="core.opencourtapplication",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_pdfs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "PDF Application",
                "verbose_name_plural": "PDF Applications",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
