# Generated by Django 6.0.1 on 2026-02-22 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_pdfapplication"),
    ]

    operations = [
        migrations.AddField(
            model_name="opencourtapplication",
            name="stipulated_time",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="opencourtapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("HEARD", "Heard"),
                    ("REFERRED", "Referred to Legal Assistance"),
                    ("CLOSED", "Closed"),
                    ("BLOCKED", "Blocked"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
