# Generated by Django 6.0.1 on 2026-03-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_opencourtapplication_stipulated_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opencourtapplication",
            name="sr_no",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
